trunk/Implementação/Fa7TapiocaDelivery/grails-app/domain/fa7tapiocadelivery/Cardapio.groovy
package fa7tapiocadelivery

class Cardapio {

    String nome
    String tipo
    Integer porcao
    

    static hasMany = [ingredientes : Ingrediente]

    static constraints = {
        nome(blank:false)
        ingredientes(nullable:false)
    }

    public String toString(){
        return getNome()
    }
}

trunk/Implementação/Fa7TapiocaDelivery/grails-app/domain/fa7tapiocadelivery/Pedido.groovy
package fa7tapiocadelivery

class Pedido {

    String descricao
 //   Usuario usuario
    Double valor
    //ArrayList<Tapioca> itens
    String status
    //StatusPedido status
    Integer quantidade
    String dataPedido

    static hasMany = [cardapios:Cardapio]

    static belongsTo = [cliente:Cliente]


    static constraints = {
        status(blank:false, inList:["S", "E", "T", "F", "C"])
        valor(nullable:false)
        dataPedido(blank:false)
        cardapios(nullable:false)
    }

    
}

trunk/Implementação/Fa7TapiocaDelivery/grails-app/controllers/fa7tapiocadelivery/PedidoController.groovy
package fa7tapiocadelivery

class PedidoController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index = {

        if(session.user){
            redirect(action: "listSol", params: params)
        }else{
            flash.message = "É necessário logar"
            redirect(url:"/Fa7TapiocaDelivery")
        }
        
    }

    def listSol = {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        //[pedidoInstanceList: Pedido.list(params), pedidoInstanceTotal: Pedido.count()]
        [pedidoInstanceList: Pedido.findByStatus("S"), pedidoInstanceTotal: Pedido.count()]
    }

    def listExe = {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [pedidoInstanceList: Pedido.findByStatus("E"), pedidoInstanceTotal: Pedido.count()]
    }

     def listTra = {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [pedidoInstanceList: Pedido.findByStatus("T"), pedidoInstanceTotal: Pedido.count()]
    }

     def listFin = {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [pedidoInstanceList: Pedido.findByStatus("F"), pedidoInstanceTotal: Pedido.count()]
    }

     def listCan = {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [pedidoInstanceList: Pedido.findByStatus("C"), pedidoInstanceTotal: Pedido.count()]
    }


    def create = {
        def pedidoInstance = new Pedido()
        pedidoInstance.properties = params
        return [pedidoInstance: pedidoInstance]
    }

    def save = {
        def pedidoInstance = new Pedido(params)
        if (pedidoInstance.save(flush: true)) {
            flash.message = "${message(code: 'default.created.message', args: [message(code: 'pedido.label', default: 'Pedido'), pedidoInstance.id])}"
            redirect(action: "show", id: pedidoInstance.id)
        }
        else {
            render(view: "create", model: [pedidoInstance: pedidoInstance])
        }
    }

    def show = {
        def pedidoInstance = Pedido.get(params.id)
        if (!pedidoInstance) {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'pedido.label', default: 'Pedido'), params.id])}"
            redirect(action: "listSol")
        }
        else {
            [pedidoInstance: pedidoInstance]
        }
    }

    def edit = {
        def pedidoInstance = Pedido.get(params.id)
        if (!pedidoInstance) {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'pedido.label', default: 'Pedido'), params.id])}"
            redirect(action: "listSol")
        }
        else {
            return [pedidoInstance: pedidoInstance]
        }
    }

    def update = {
        def pedidoInstance = Pedido.get(params.id)
        if (pedidoInstance) {
            if (params.version) {
                def version = params.version.toLong()
                if (pedidoInstance.version > version) {
                    
                    pedidoInstance.errors.rejectValue("version", "default.optimistic.locking.failure", [message(code: 'pedido.label', default: 'Pedido')] as Object[], "Another user has updated this Pedido while you were editing")
                    render(view: "edit", model: [pedidoInstance: pedidoInstance])
                    return
                }
            }
            pedidoInstance.properties = params
            if (!pedidoInstance.hasErrors() && pedidoInstance.save(flush: true)) {
                flash.message = "${message(code: 'default.updated.message', args: [message(code: 'pedido.label', default: 'Pedido'), pedidoInstance.id])}"
                redirect(action: "listSol", id: pedidoInstance.id)
            }
            else {
                render(view: "edit", model: [pedidoInstance: pedidoInstance])
            }
        }
        else {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'pedido.label', default: 'Pedido'), params.id])}"
            redirect(action: "listSol")
        }
    }

    def delete = {
        def pedidoInstance = Pedido.get(params.id)
        if (pedidoInstance) {
            try {
                pedidoInstance.delete(flush: true)
                flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'pedido.label', default: 'Pedido'), params.id])}"
                redirect(action: "listSol")
            }
            catch (org.springframework.dao.DataIntegrityViolationException e) {
                flash.message = "${message(code: 'default.not.deleted.message', args: [message(code: 'pedido.label', default: 'Pedido'), params.id])}"
                redirect(action: "show", id: params.id)
            }
        }
        else {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'pedido.label', default: 'Pedido'), params.id])}"
            redirect(action: "listSol")
        }
    }
    
    def consultarstatus = {
		
		if (params){
			[ pedido: Pedido.get(params.id)]
			//if pedido == null 
			//pedido.set( mostrarStatus = true )
			//pedido.params.mostrarStatus = true
		}
		else{
			//pedido.set( mostrarStatus = false )
			//pedido.params.mostrarStatus = false
		}
	}
	
	
    def preparestatus = { 
	    
		def pedidoInstance = new Pedido()
		pedidoInstance.properties = params
		[pedidoInstance: pedidoInstance]
		render(view: "consultarstatus", model: [pedidoInstance: pedidoInstance])
    }
}

trunk/Implementação/Fa7TapiocaDelivery/grails-app/views/pedido/consultarstatus.gsp

<%@ page import="fa7tapiocadelivery.Pedido" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'pedido.label', default: 'Consultar Status Pedido')}" />
    </head>
    <body>
	<div class="nav">
		 <span class="menuButton"><a href="http://google.com/">Teste</a></span>
		</div>
	    <h1> Consultar Status </h1>
        <p> Entre com o numero do pedido para consultar o status </p>
		
		 <g:hasErrors bean="${pedido}">
			<div class="errors">
				<g:renderErrors bean="${pedido}"></g:renderErrors>
			</div>
	    </g:hasErrors>
        <div class="body">
			<g:form action="consultarstatus" name="consultarstatusForm">
			    <br>
				<div class="formField">            
					<label for="pedido">Numero Pedido:</label>
					<g:textField name="id" value="${pedidoInstance?.id}"/>
					<!-- <g:set var="numPedido" value="${pedidoInstance?.id}" />
					-->
				</div>
				<div class="buttons">
					<span class="button"><g:actionSubmit class="consultarstatus" action="consultarstatus" value="${message(code: 'default.button.status.label', default: 'Pesquisar Status')}" /></span>
				</div>
			</g:form>
			
			<g:if test="${pedido?.id != null}">
				<table>
					<tbody>
						<br>
							<tr class="prop">
							<td valign="top" class="name"><b>Status do pedido ${fieldValue(bean: pedido, field: "id")}:</td>	
							<td valign="top" class="value">${fieldValue(bean: pedido, field: "status")}</td>
						</tr>
					</tbody>
				</table>
			</g:if>	 	
        </div>
    </body>
</html>

trunk/Implementação/Fa7TapiocaDelivery/grails-app/views/pedido/create.gsp
<%@ page import="fa7tapiocadelivery.Pedido" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'pedido.label', default: 'Pedido')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
            <span class="menuButton"><g:link class="list" action="listSol"><g:message code="default.list.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${pedidoInstance}">
              <div class="errors">
                <g:renderErrors bean="${pedidoInstance}" as="list" />
            </div>
            </g:hasErrors>

            <g:if test="${session.user}">
              <br />
              Logado como: ${session.user.nome} | <g:link action="logout">logout</g:link>
            </g:if>

            <g:form action="save" method="post" >
                <div class="dialog">
                    <table>
                        <tbody>

                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="cliente">Cliente</label>
                                </td>
                                <td valign="top" class="value">
                                        ${session.user.nome}
                                        <g:hiddenField name="cliente.id" value="${session?.user?.id}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="quantidade"><g:message code="pedido.quantidade.label" default="Quantidade" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'quantidade', 'errors')}">
                                    <g:textField name="quantidade" value="${fieldValue(bean: pedidoInstance, field: 'quantidade')}" />
                                </td>
                            </tr>

                            <!--
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="valor"><g:message code="pedido.valor.label" default="Valor" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'valor', 'errors')}">
                                    <g:textField name="valor" value="${fieldValue(bean: pedidoInstance, field: 'valor')}" />
                                </td>
                            </tr>
                            -->
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="status"><g:message code="pedido.status.label" default="Status" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'status', 'errors')}">
                                    <g:textField name="status" value="S" readonly="yes"/>
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="descricao"><g:message code="pedido.descricao.label" default="Descricao" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'descricao', 'errors')}">
                                    <g:textField name="descricao" value="${pedidoInstance?.descricao}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="dataPedido"><g:message code="pedido.dataPedido.label" default="Data Pedido" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'dataPedido', 'errors')}">
                                    <g:textField name="dataPedido" value="10/06/2010" readonly="yes"/>
                                </td>
                            </tr>


                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="cardapios"><g:message code="pedido.cardapios.label" default="Itens Cardapio" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoIntance, field: 'cardapios', 'errors')}">
                                    <g:select name="cardapios" from="${fa7tapiocadelivery.Cardapio.list()}" multiple="yes" optionKey="id" size="5" value="${pedidoInstance?.cardapios}" />
                                </td>
                            </tr>

                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

trunk/Implementação/Fa7TapiocaDelivery/grails-app/views/pedido/edit.gsp
<%@ page import="fa7tapiocadelivery.Pedido" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'pedido.label', default: 'Pedido')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
            <span class="menuButton"><g:link class="listSol" action="listSol"><g:message code="Pedidos Solicitados" args="[entityName]" /></g:link></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="Novo Pedido" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${pedidoInstance}">
            <div class="errors">
                <g:renderErrors bean="${pedidoInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form method="post" >
                <g:hiddenField name="id" value="${pedidoInstance?.id}" />
                <g:hiddenField name="version" value="${pedidoInstance?.version}" />
                <div class="dialog">
                    <table>
                        <tbody>

                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="cliente">Cliente</label>
                                </td>
                                <td valign="top" class="value">
                                        ${session.user.nome}
                                        <g:hiddenField name="cliente.id" value="${session?.user?.id}" />
                                </td>
                            </tr>

                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="dataPedido"><g:message code="pedido.dataPedido.label" default="Data Pedido" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'dataPedido', 'errors')}">
                                    <g:textField name="dataPedido" value="${pedidoInstance?.dataPedido}"  readonly="true" />
                                </td>
                            </tr>

                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="descricao"><g:message code="pedido.descricao.label" default="Descricao" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'descricao', 'errors')}">
                                    <g:textField name="descricao" value="${pedidoInstance?.descricao}"  readonly="true" />
                                </td>
                            </tr>

                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="quantidade"><g:message code="pedido.quantidade.label" default="Quantidade" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'quantidade', 'errors')}">
                                    <g:textField name="quantidade" value="${fieldValue(bean: pedidoInstance, field: 'quantidade')}" readonly="true" />
                                </td>
                            </tr>
                            <!--
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="valor"><g:message code="pedido.valor.label" default="Valor" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'valor', 'errors')}">
                                    <g:textField name="valor" value="${fieldValue(bean: pedidoInstance, field: 'valor')}"  readonly="true" />
                                </td>
                            </tr>
                            -->
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="status"><g:message code="pedido.status.label" default="Status" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: pedidoInstance, field: 'status', 'errors')}">
                                    <g:textField name="status" value="${pedidoInstance?.status}" />
                                </td>
                            </tr>

                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="cardapios"><g:message code="pedido.cadapios.label" default="Itens Cardapio" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: cardapioInstance, field: 'cardapios', 'errors')}">
                                    <g:select name="cardapios" from="${fa7tapiocadelivery.Cardapio.list()}" multiple="yes" optionKey="id" size="5" value="${pedidoInstance?.cardapios}" />
                                </td>
                            </tr>
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" /></span>
                    <span class="button"><g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

trunk/Implementação/Fa7TapiocaDelivery/grails-app/views/pedido/list1.gsp
<%@ page import="fa7tapiocadelivery.Pedido" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'pedido.label', default: 'Pedido')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="list">
                <table>
                    <thead>
                        <tr>
                        
                            <g:sortableColumn property="id" title="${message(code: 'pedido.id.label', default: 'Id')}" />
                        
                            <g:sortableColumn property="quantidade" title="${message(code: 'pedido.quantidade.label', default: 'Quantidade')}" />
                        
                            <g:sortableColumn property="valor" title="${message(code: 'pedido.valor.label', default: 'Valor')}" />
                        
                            <g:sortableColumn property="status" title="${message(code: 'pedido.status.label', default: 'Status')}" />
                        
                            <th><g:message code="pedido.cliente.label" default="Cliente" /></th>
                   	    
                            <g:sortableColumn property="descricao" title="${message(code: 'pedido.descricao.label', default: 'Descricao')}" />
                        
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${pedidoInstanceList}" status="i" var="pedidoInstance">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="show" id="${pedidoInstance.id}">${fieldValue(bean: pedidoInstance, field: "id")}</g:link></td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "quantidade")}</td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "valor")}</td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "status")}</td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "cliente")}</td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "descricao")}</td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
            <div class="paginateButtons">
                <g:paginate total="${pedidoInstanceTotal}" />
            </div>
        </div>
    </body>
</html>

trunk/Implementação/Fa7TapiocaDelivery/grails-app/views/pedido/listCan.gsp
<%@ page import="fa7tapiocadelivery.Pedido" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'pedido.label', default: 'Pedido')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
            <span class="menuButton"><g:link class="listSol" action="listSol"><g:message code="Pedidos Solicitados" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="Pedidos Cancelados" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="listCan">
                <table>
                    <thead>
                        <tr>
                        
                            <g:sortableColumn property="id" title="${message(code: 'pedido.id.label', default: 'Id')}" />

                            <th><g:message code="pedido.cliente.label" default="Cliente" /></th>

                            <g:sortableColumn property="descricao" title="${message(code: 'pedido.descricao.label', default: 'Descricao')}" />

                            <g:sortableColumn property="quantidade" title="${message(code: 'pedido.quantidade.label', default: 'Quantidade')}" />

                            <g:sortableColumn property="valor" title="${message(code: 'pedido.valor.label', default: 'Valor')}" />

                            <g:sortableColumn property="status" title="${message(code: 'pedido.status.label', default: 'Status')}" />
                        
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${pedidoInstanceList}" status="i" var="pedidoInstance">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="edit" id="${pedidoInstance.id}">${fieldValue(bean: pedidoInstance, field: "id")}</g:link></td>

                            <td>${fieldValue(bean: pedidoInstance, field: "cliente")}</td>

                            <td>${fieldValue(bean: pedidoInstance, field: "descricao")}</td>

                            <td>${fieldValue(bean: pedidoInstance, field: "quantidade")}</td>

                            <td>${fieldValue(bean: pedidoInstance, field: "valor")}</td>

                            <td>${fieldValue(bean: pedidoInstance, field: "status")}</td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
            <div class="paginateButtons">
                <g:paginate total="${pedidoInstanceTotal}" />
            </div>
        </div>
    </body>
</html>

trunk/Implementação/Fa7TapiocaDelivery/grails-app/views/pedido/listEnt.gsp
<%@ page import="fa7tapiocadelivery.Pedido" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'pedido.label', default: 'Pedido')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
            <span class="menuButton"><g:link class="listTra" action="listTra"><g:message code="Pedido em Trânsito" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="listTra">
                <table>
                    <thead>
                        <tr>
                        
                            <g:sortableColumn property="id" title="${message(code: 'pedido.id.label', default: 'Id')}" />
                        
                            <g:sortableColumn property="quantidade" title="${message(code: 'pedido.quantidade.label', default: 'Quantidade')}" />
                        
                            <g:sortableColumn property="valor" title="${message(code: 'pedido.valor.label', default: 'Valor')}" />
                        
                            <g:sortableColumn property="status" title="${message(code: 'pedido.status.label', default: 'Status')}" />
                        
                            <th><g:message code="pedido.cliente.label" default="Cliente" /></th>
                   	    
                            <g:sortableColumn property="descricao" title="${message(code: 'pedido.descricao.label', default: 'Descricao')}" />
                        
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${pedidoInstanceList}" status="i" var="pedidoInstance">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="show" id="${pedidoInstance.id}">${fieldValue(bean: pedidoInstance, field: "id")}</g:link></td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "quantidade")}</td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "valor")}</td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "status")}</td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "cliente")}</td>
                        
                            <td>${fieldValue(bean: pedidoInstance, field: "descricao")}</td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
            <div class="paginateButtons">
                <g:paginate total="${pedidoInstanceTotal}" />
            </div>
        </div>
    </body>
</html>